language: ruby
sudo: false
gemfile: nubis/travis/Gemfile
cache:
  bundler: true
  directories:
  - "${HOME}/bin"
  - nubis/librarian-puppet
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
script:
- nubis/travis/run-checks
notifications:
  slack:
    secure: k6pLsoz+jPbqAIA7eqmIeOVqStluF1B1f0EcloZMk41yj+OJZYmDpK3iCO2OdSnmeKDVhZJngE5ovroMlV+H/dWrJkZhHpJX0CYoe1vPxFOEu+JV5A95xpYbJFnHL9s1mJ9RTRMJYA03lRwrMiMYwZxCjGyjSnsPInvRPzE4WpQ=
